### ISSUE TITLE
Duplicated mapping key in JSON files

### ISSUE THREAD

**Issue by mmontone** [nknapp/bootprint-openapi#54]
Hello.

When I try to bootprint from a json file, I get:

```
marian@gimli ~/bootprint $ bootprint openapi ./calendar.json calendar
Loading bootprint-openapi 0.14.0
Loading bootprint-json-schema 0.8.4
Loading bootprint-base 0.6.3

/usr/lib/node_modules/bootprint/node_modules/q/q.js:155
                throw e;
                ^
YAMLException: duplicated mapping key at line 1, column 33806:
     ... "The content","required":true}]},"delete":{"method":"DELETE","su ... 
                                         ^
    at generateError (/usr/lib/node_modules/bootprint/node_modules/js-yaml/lib/js-yaml/loader.js:161:10)
    at throwError (/usr/lib/node_modules/bootprint/node_modules/js-yaml/lib/js-yaml/loader.js:167:9)
    at storeMappingPair (/usr/lib/node_modules/bootprint/node_modules/js-yaml/lib/js-yaml/loader.js:304:7)
    at readFlowCollection (/usr/lib/node_modules/bootprint/node_modules/js-yaml/lib/js-yaml/loader.js:719:7)
    at composeNode (/usr/lib/node_modules/bootprint/node_modules/js-yaml/lib/js-yaml/loader.js:1328:11)
    at readFlowCollection (/usr/lib/node_modules/bootprint/node_modules/js-yaml/lib/js-yaml/loader.js:714:7)
    at composeNode (/usr/lib/node_modules/bootprint/node_modules/js-yaml/lib/js-yaml/loader.js:1328:11)
    at readFlowCollection (/usr/lib/node_modules/bootprint/node_modules/js-yaml/lib/js-yaml/loader.js:714:7)
    at composeNode (/usr/lib/node_modules/bootprint/node_modules/js-yaml/lib/js-yaml/loader.js:1328:11)
    at readBlockMapping (/usr/lib/node_modules/bootprint/node_modules/js-yaml/lib/js-yaml/loader.js:1002:16)
```

Now, I don't see any duplicate entry. What's more, if I convert the json to yaml (for example, using http://jsontoyaml.com/), and then run bootprint the yaml file, it just works.

**Comment by mmontone** [comment]
Mmm..it actually works if I paste the JSON to the bootprint-openapi online service. I may be using some old package, maybe.

**Comment by nknapp** [comment]
I can't tell unless you show me the calendar JSON. However the exception is thrown by `js-yaml` so maybe you could check the version of that package. The online-service is using `js-yaml@3.4.6` in the browser to convert the input to JSON. Can you post your JSON or send me an e-mail?

`bootprint` uses the `yaml.safeLoad` method to load the JSON file.

I would  first verify that the JSON is valid. 

```js
var fs = require('fs')
var data = JSON.parse(fs.readFileSync('./calendar.json')
```

Then verify that `js-yaml` cannot convert it.

```js
var yaml = require('js-yaml')
var fs = require('fs')
var data = yaml.safeLoad(fs.readFileSync('./calendar.json')
```
Since `yaml` is a superset of JSON, `js-yaml` should be able to read any valid JSON-file. If not, I would file a bug with `js-yaml`.

**Comment by nknapp** [comment]
I'm closing this issue due to lack of response. Please comment here if anything new arises.
